# 버전은 0.0 os는 linux로 고정
version: 0.0
os: linux

# file는 아래에 source는 복사해서 보낼 것들에 대해서 명시하는 것이다.
# destinatioin은 복사할 위치이다.
files:
  # dist 폴더 복사
  - source: /
    destination: /home/ec2-user/workspace/readinggate-rest-api-nest-server
    file_exists_behavior: OVERWRITE

# permissions는 복사한 폴더에 권한을 부여하는 역할이다.    
permissions:
  - object: /home/ec2-user/workspace/readinggate-rest-api-nest-server

# hooks는 해당 상황에 따른 실행할 스크립트들을 넣어준다.
hooks:
  BeforeInstall:
    - location: ./scripts/before-install.sh
      timeout: 900
      
  AfterInstall:
    - location: ./scripts/after-install.sh
      timeout: 900
      
  ApplicationStart:
    - location: ./scripts/application-start.sh
      timeout: 900