version: 0.0
os: linux
files:
  - source: /dist
    destination: /usr/share/nginx/server/
    
permissions:
  - object: /home/ec2-user/workspace/
    owner: root
    group: root
      
hooks:
  ApplicationStop:
    - location: 
      timeout:
      runas:
    - location: 
      timeout:
      runas: 
      
  BeforeInstall:
    - location: 
      timeout:
      runas: 
    - location: 
      timeout:
      runas:
      
  AfterInstall:
    - location:     
      timeout: 
      runas:
    - location: 
      timeout:
      runas:
      
  ApplicationStart:
    - location:     
      timeout: 
      runas:
    - location: 
      timeout:
      runas:
      
  ValidateService:
    - location:     
      timeout: 
      runas:
    - location: 
      timeout:
      runas: