name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main
    
jobs:
  build:
    runs-on: linux
    
    steps:
      - name: just go
            
      - name: aws --version
      
      # s3
      - name: sync bucket
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          
        run: |
          aws s3 sync ./ s3://rg-7th-bucket