name: CI
on:
  push:
    branches: main
  pull_request:
    branches: main
    
jobs:
  build:
    runs-on: linux
    
    steps:
      - name: git clone
        uses: actions/checkout@v2
              
      # s3
      - name: sync bucket
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          
        run: | 
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://rg-7th-bucket